# Site settings
title: Cheap and Cheerful Stream Restoration
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Some site description will go here
baseurl: /web_anabranch
url: https://anabranchsolutions.github.io/web_anabranch
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown


defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "page"

sass:
    sass_dir: node_modules/foundation-sites/scss
    style: compressed

exclude:
  - LICENSE
  - package.json
  - README.md