# Site settings
title: Cheap and Cheerful Stream Restoration
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Some site description will go here
url: "https://mattreimer.github.io/gitbook-test"
baseurl: "gitbook-test"
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown


defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "page"
